// <auto-generated />
namespace QuotationApp.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Update001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update001));
        
        string IMigrationMetadata.Id
        {
            get { return "201505140406066_Update001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
