// <auto-generated />
namespace QuotationApp.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Upadate006 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Upadate006));
        
        string IMigrationMetadata.Id
        {
            get { return "201505171443042_Upadate006"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
